import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ActionButton from '../components/actionButton.js';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        Stromeček 🎄
      </h1>
      
        <div className={'my-8 mx-auto max-w-md grid grid-cols-3 gap-4 content-start '}>
          <ActionButton action={'glow'}>
            Zář
          </ActionButton>
          <ActionButton action={'seq'}>Blikání</ActionButton>
          <ActionButton action={'dim'}>Ztlum</ActionButton>
          <ActionButton action={'col-yellow'}>Žlutá</ActionButton>
          <ActionButton action={'col-mid'}>Neutrální</ActionButton>
          <ActionButton action={'sch'}>Sám se měň</ActionButton>
        </div>

    </div>
  )
}
